### ISSUE TITLE
Numix-Dark icon theme - request for white (light gray) icons for dark panels.

### ISSUE THREAD

**Issue by nbvcxz** [cldx/numix#5]
Numix icon theme is awesome, but one of the missing important features is icon set for dark panels and backgrounds. As corresponding Numix gtk theme is a dark theme there would be nice to have something like Faenza-Dark: the icon theme to match dark background panels.

**Comment by cldx** [comment]
First iterations of a light variant can be found here : https://github.com/cldx/numix-light
Feel free to try it out and report any Issues you're having :)
